<?php


namespace backend\controllers;


use backend\models\Contacts;
use backend\models\Media;
use backend\models\UploadForm;
use common\helper\Helper;
use yii\base\Exception;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class AjaxImportController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->response->format = Response::FORMAT_JSON;
    }

    /**
     * @return bool
     * @throws BadRequestHttpException
     */
    public function actionContact()
    {
        $data = \Yii::$app->request->post('row');
        $model = new Contacts();
        if ($model->load($data, '')) {
            if (!$model->save()) {
                throw new BadRequestHttpException(Helper::firstError($model));
            }
        }
        return true;
    }

    /**
     * @return bool
     * @throws BadRequestHttpException
     */
    public function actionTrackingNumber()
    {
        $data = \Yii::$app->request->post('row');
        $model = Contacts::findOne(['code' => $data['code']]);
        if (!$model) {
            throw new BadRequestHttpException('Không tìm thấy đơn hàng!');
        }
        return true;
    }
}