<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'today_completed' => 'Today completed',
    'contact' => 'Contacts',
    'contact_histories' => 'Contact histories',
    'contact_all' => 'All contacts',
    'new_contact' => 'New Contact',
    'pending_contact' => 'Pending',
    'cancel_contact' => 'Cancel',
    'success_contact' => 'Success',
    'fail_contact' => 'Number fail',
    'callback_contact' => 'Callback',
    'duplicate_contact' => 'Duplicate',
    'customer_information' => 'Customer information',
    'product' => 'Product',
    'customer' => 'Customer',
    'partner' => 'Partner',
    'phone' => 'Phone',
    'zipcode' => 'Zipcode',
    'address' => 'Address',
    'district' => 'District',
    'province' => 'Province',
    'city' => 'City',
    'country' => 'Country',
    'payment_method' => 'Payment method',
    'shipping_fee' => 'Shipping fee',
    'contact_source' => 'Contact source',
    'order_note' => 'Order note',
    'delivery_note' => 'Delivery note',
    'qty' => 'Qty',
    'amount' => 'Amount',
    'total_amount' => 'Total amount',
    'warehouse' => 'Warehouse',
    'product_type' => 'Product type',
    'available' => 'Available',
    'save' => 'Save',
    'cancel' => 'Cancel',
    'create' => 'Create',
    'warehouse_status' => 'Warehouse status',
    'create_order' => 'Create order',
    'buy_option' => 'Buy option',
    'contact_status' => 'Contact status',
    'register_time' => 'Contact date',
    'created_at' => 'Created at',
    'updated_at' => 'Updated at',
    'note' => 'Note',
    'order_code' => 'Order code',
    'contact_code' => 'Contact code',
    'bill_link' => 'Billing image',
    'delivery_partner' => 'Delivery partner',
    'checking_number' => 'Tracking number',
    'payment_status' => 'Payment status',
    'cross_status' => 'Cross check status',
    'shipping_status' => 'Shipping status',
    'po_code' => 'PO',
    'order_time' => 'Order time',
    'sub_transport' => 'Delivery partner sub',
    'sub_transport_code' => 'Tracking number sub',
    'cod_cost' => 'COD',
    'time_shipped_success' => 'Time shipping success',
    'collection_fee' => 'Collection fee',
    'transport_fee' => 'Transport fee',
    'delivery_fee' => 'Delivery fee',
    'cross_check_code' => 'Cross check code',
    'cross_check_time' => 'cross_check_time',
    'time_paid_success' => 'Payment date',
    'callback_reason' => 'Callback reason',
    'other_reason' => 'Other reason',
    'variant' => 'Variant',
    'Liên hệ' => 'Contacts',
    'Lịch sử cuộc gọi' => 'Contact histories',
    'Liên hệ tổng hợp' => 'All contacts',
    'required_note' => 'Fields required',
    'close' => 'Close',
    'call_note' => 'Call note',
    'ok' => 'OK',
    'callback' => 'Callback',
    'number_fail' => 'Number fail',
    'pending' => 'Pending',
    'duplicate' => 'Duplicate',
];
