<?php

namespace backend\models;

use common\helper\Helper;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\BadRequestHttpException;

/**
 * This is the model class for table "orders_contact".
 *
 * @property int $id
 * @property string $name
 * @property string $phone
 * @property string|null $code
 * @property string $address
 * @property string $zipcode
 * @property float|null $shipping_cost
 * @property int|null $payment_method
 * @property string|null $email
 * @property string|null $city
 * @property string|null $district
 * @property string|null $order_source
 * @property string|null $note
 * @property string|null $vendor_note
 * @property string|null $status
 * @property int $created_at
 * @property int $updated_at
 * @property string|null $country
 * @property float|null $total_bill
 * @property float|null $total_price
 * @property int|null $warehouse_id
 * @property int|null $transport_id
 * @property string|null $checking_number
 * @property string|null $payment_status
 * @property string|null $cross_status
 * @property string|null $shipping_status
 * @property string|null $po_code
 * @property int|null $order_time
 * @property int|null $sub_transport_id
 * @property string|null $sub_transport_tracking
 * @property float|null $cod_cost
 * @property int|null $time_shipped_success
 * @property float|null $collection_fee
 * @property float|null $transport_fee
 * @property int|null $remittance_date
 * @property string|null $cross_check_code
 * @property int|null $time_paid_success
 * @property int|null $partner
 * @property float|null $service_fee
 * @property int|null $sale
 *
 * @property OrdersContactSku[] $ordersContactSkus
 */
class _OrdersContact extends \common\models\BaseModel
{

    const STATUS_NEW = 'new';
    const STATUS_PENDING = 'pending';
    const STATUS_SHIPPING = 'shipping';
    const STATUS_SHIPPED = 'shipped';


    const STATUS_PAYED = 'paid';
    const STATUS_UNPAID = 'unpaid';
    const STATUS_REFUND = 'refund';

    const STATUS_CANCEL = 'cancel';
    const STATUS_UNCROSS = 'uncross';
    const STATUS_CROSSED = 'crossed';

    const STATUS = [
        self::STATUS_NEW => 'Chưa vận chuyển',
        self::STATUS_PENDING => 'Chờ vận chuyển',
        self::STATUS_SHIPPING => 'Đang vận chuyển',
        self::STATUS_SHIPPED => 'Đã vận chuyển',
        self::STATUS_UNPAID => 'Chưa thanh toán',
        self::STATUS_PAYED => 'Đã thanh toán',
        self::STATUS_REFUND => 'Hoàn đơn',
        self::STATUS_UNCROSS => 'Chưa đối soát',
        self::STATUS_CROSSED => 'Đã đối soát',
        self::STATUS_CANCEL => 'Huỷ đơn',

    ];
    const STATIC_PAYMENT_TRANSFER = 3;
    const STATIC_PAYMENT = [
        self::STATIC_PAYMENT_TRANSFER => 'Chuyển khoản'
    ];
    /**
     * @var mixed|null
     */


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders_contact';
    }

    /**
     * {@inheritdoc}
     */
    public $cost_product;
    public $cost_bill;
    public $bill_link;
    public $partner;
    public $service_fee;
    public $sale;

    public function rules()
    {
        return [
            [['name', 'phone', 'address', 'zipcode', 'country', 'payment_method', 'shipping_cost'], 'required'],
            [['total_bill', 'total_price', 'cod_cost', 'collection_fee', 'transport_fee'], 'number'],
            [['payment_method', 'created_at', 'updated_at', 'warehouse_id', 'transport_id', 'order_time', 'sub_transport_id', 'time_shipped_success', 'remittance_date'], 'integer'],
            [['name', 'code', 'address', 'zipcode', 'email', 'city', 'district', 'order_source', 'note', 'vendor_note', 'country', 'checking_number', 'po_code', 'sub_transport_tracking', 'cross_check_code'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 25],
            [['status'], 'string', 'max' => 100],
            [['shipping_cost', 'partner'], 'safe'],
            [['bill_link'], 'string'],
            [['payment_status', 'cross_status', 'shipping_status'], 'string', 'max' => 50],
        ];
    }

    public static function find()
    {
        return parent::find()->where(['{{orders_contact}}.country' => Yii::$app->cache->get('country')]);
    }
    public function fields()
    {
        return array_merge(parent::fields(), [
            'cost_bill', 'cost_product'
        ]); // TODO: Change the autogenerated stub
    }
    public function extraFields()
    {
        $extraFields = parent::extraFields();
        $extraFields[] = 'cost_bill';
        $extraFields[] = 'cost_product';
        return $extraFields;
        // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => Yii::t('app', 'customer'),
            'phone' => Yii::t('app', 'phone'),
            'code' => Yii::t('app', 'order_code'),
            'partner' => Yii::t('app', 'partner'),
            'address' => Yii::t('app', 'address'),
            'zipcode' => Yii::t('app', 'zipcode'),
            'shipping_cost' => Yii::t('app', 'shipping_fee'),
            'payment_method' => Yii::t('app', 'payment_method'),
            'email' => 'Email',
            'city' => Yii::t('app', 'province'),
            'district' => Yii::t('app', 'district'),
            'order_source' => Yii::t('app', 'contact_source'),
            'note' => Yii::t('app', 'order_note'),
            'vendor_note' => Yii::t('app', 'delivery_note'),
            'status' => Yii::t('app', 'status'),
            'created_at' => Yii::t('app', 'created_at'),
            'updated_at' => Yii::t('app', 'updated_at'),
            'country' => Yii::t('app', 'country'),
            'total_bill' => Yii::t('app', 'total_amount'),
            'bill_link' => Yii::t('app', 'bill_link'),
            'total_price' => Yii::t('app', 'amount'),
            'warehouse_id' => Yii::t('app', 'warehouse'),
            'transport_id' => Yii::t('app', 'delivery_partner'),
            'checking_number' => Yii::t('app', 'tracking_number'),
            'payment_status' => Yii::t('app', 'payment_status'),
            'cross_status' => Yii::t('app', 'cross_status'),
            'shipping_status' => Yii::t('app', 'shipping_status'),
            'po_code' => Yii::t('app', 'po_code'),
            'order_time' => Yii::t('app', 'order_time'),
            'sub_transport_id' => Yii::t('app', 'sub_transport'),
            'sub_transport_tracking' => Yii::t('app', 'sub_transport_code'),
            'cod_cost' => Yii::t('app', 'cod_cost'),
            'time_shipped_success' => Yii::t('app', 'time_shipped_success'),
            'collection_fee' => Yii::t('app', 'collection_fee'),
            'transport_fee' => Yii::t('app', 'transport_fee'),
            'remittance_date' => Yii::t('app', 'cross_check_time'),
            'cross_check_code' => Yii::t('app', 'cross_check_code'),
            'time_paid_success' => Yii::t('app', 'time_paid_success'),
        ];
    }
    /**
     * Gets query for [[OrdersContactSkus]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSkuItems()
    {
        return $this->hasMany(OrdersContactSku::className(), ['order_id' => 'id'])->with('product');
    }
    public function getContact()
    {
        return $this->hasOne(Contacts::className(), ['code' => 'code'])->with('partner');
    }
    public function getWarehouse()
    {
        return $this->hasOne(Warehouse::className(), ['id' => 'warehouse_id']);
    }
    public function getPayment()
    {
        return $this->hasOne(Payments::className(), ['id' => 'payment_method']);
    }
    public function getTransporter()
    {
        return $this->hasOne(Transporters::className(), ['id' => 'transport_id']);
    }
    public function beforeSave($insert)
    {
        if (!Helper::isEmpty($this->shipping_cost)) {
            $this->shipping_cost = Helper::toFloat($this->shipping_cost);
        }
        if (!Helper::isEmpty($this->total_bill)) {
            $this->total_bill = Helper::toFloat($this->total_bill);
        }
        if (!Helper::isEmpty($this->total_price)) {
            $this->total_price = Helper::toFloat($this->total_price);
        }
        if (Helper::isEmpty($this->code)) {
            try {
                $partner = UserModel::findOne($this->partner);
                $this->partner = $partner->username;
                $this->code = Contacts::generateCode($this->partner, $this->country);

            } catch (BadRequestHttpException $e) {
                $this->addError('code', $e->getMessage());
                return false;
            }
        }
        if ($insert) {
            if ($this->payment_method === self::STATIC_PAYMENT_TRANSFER && Helper::isEmpty($this->bill_link)) {
                $this->addError("bill_link", "Link hóa đơn chuyển khoản trống!");
                return false;
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public static function StatusLabel($status)
    {
        switch ($status) {
            case self::STATUS_NEW:
                $color = 'primary';
                break;
            case self::STATUS_PENDING:
                $color = 'info';
                break;
            case self::STATUS_SHIPPING:
                $color = 'warning';
                break;
            default:
                $color = 'success';
        }
        return Html::tag('span', ArrayHelper::getValue(self::STATUS, $status, '--'), [
            'class' => "badge badge-pill m-auto badge-$color"
        ]);
    }
}
