<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "categories".
 *
 * @property int $id
 * @property string $name
 * @property string|null $country
 * @property int $partner_id
 * @property string|null $description
 * @property int $created_at
 * @property int $updated_at
 */
class Categories extends \common\models\BaseModel
{
    /**
     * @var mixed|null
     */
    private $partner;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'partner_id', 'country'], 'required'],
            [['partner_id', 'created_at', 'updated_at'], 'integer'],
            [['name', 'country', 'description'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên loại sản phẩm',
            'country' => 'Thị trường',
            'partner_id' => 'Đối tác',
            'description' => 'Mô tả',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Updated At',
        ];
    }

    public function getPartner()
    {
        return $this->hasOne(UserModel::className(), ['id' => 'partner_id']);
    }

    public function afterFind()
    {
        $this->generateName();
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    private function generateName()
    {
        $partner = UserModel::findOne($this->partner_id);
        if (!$partner) {
            $this->addError('partner_id', 'Không tìm thấy đối tác!');
            return false;
        }
        $this->name = $this->country . '-' . $partner->username . '-' . $this->name;
    }

    static function LISTS()
    {
        $categories = Categories::find()->addSelect(['id', 'name'])->all();
        return ArrayHelper::map($categories, 'id', 'name');
    }
}
