<?php

namespace backend\models;

use common\helper\Helper;
use Yii;

/**
 * This is the model class for table "orders_topup".
 *
 * @property int $id
 * @property int $time
 * @property string $cash_source
 * @property string $avatar
 * @property int|null $partner_id
 * @property int|null $thumb
 * @property float|null $total
 * @property int $created_at
 * @property int $updated_at
 */
class OrdersTopup extends \common\models\BaseModel
{
    /**
     * {@inheritdoc}
     */
    public $avatar;
    public $thumb;

    const SOURCE_COD = 'cod';
    const SOURCE_CASH = 'cash';
    const SOURCE = [
        self::SOURCE_COD => 'Số dư COD',
        self::SOURCE_CASH => 'Tiền mặt'
    ];

    public static function tableName()
    {
        return 'orders_topup';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['time', 'cash_source', 'partner_id', 'total'], 'required'],
            [['partner_id', 'created_at', 'updated_at'], 'integer'],
            [['total'], 'number'],
            [['cash_source', 'time'], 'string', 'max' => 255],
            [['avatar', 'thumb'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getMedias()
    {
        return $this->hasOne(MediaObj::className(), ['obj_id' => 'id'])
            ->where(['{{media_obj}}.obj_type' => MediaObj::OBJECT_TOPUP])
            ->with('media');
    }

    public function getPartner()
    {
        return $this->hasOne(UserModel::className(), ['id' => 'partner_id']);
    }

    public function beforeSave($insert)
    {
        if (!Helper::isEmpty($this->time)) {
            $this->time = Helper::timer(str_replace("/", "-", $this->time));
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'time' => 'Time',
            'cash_source' => 'Nguồn tiền',
            'partner_id' => 'Đối tác',
            'total' => 'Số tiền',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


}
