<?php


namespace backend\models;


use common\helper\Helper;

class OrderCrossStatus extends OrdersContact
{
    public $ids;
    public $partner;
    public $country;
    public $cross_count;

    public function rules()
    {
        return [
            [['country', 'partner', 'cross_count', 'ids'], 'safe'],
            [['country', 'partner', 'cross_count','remittance_date'], 'required'],
            [['cross_check_code'], 'unique']
        ];
    }

    public function beforeSave($insert)
    {
        $recode = $this->remittance_date;
        $recode = str_replace("/", "", $recode);
        $this->remittance_date = Helper::timer(str_replace("/", "-", $this->remittance_date));
        $this->cross_check_code = "BB-{$recode}-{$this->country}-{$this->partner}-{$this->cross_count}";

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}