<?php

namespace backend\models;

use common\helper\Helper;
use Yii;

/**
 * This is the model class for table "orders_example".
 *
 * @property int $id
 * @property string|null $category
 * @property string|null $option
 * @property float|null $total_bill
 * @property int $created_at
 * @property int $updated_at
 *
 * @property OrdersExampleItem[] $ordersExampleItems
 */
class OrdersExample extends \common\models\BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders_example';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['option','total_bill'], 'string'],
            [['option', 'total_bill', 'category'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['category'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function beforeSave($insert)
    {
        $this->total_bill = Helper::toFloat($this->total_bill);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category' => 'Loại sản phẩm',
            'option' => 'Yêu cầu',
            'total_bill' => 'Tổng cộng',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[OrdersExampleItems]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSkuItems()
    {
        return $this->hasMany(OrdersExampleItem::className(), ['order_example_id' => 'id']);
    }
}
