<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'today_completed' => 'Hoàn thành hôm nay',
    'contact' => 'Liên hệ',
    'contact_histories' => 'Lịch sử cuộc gọi',
    'contact_all' => 'Liên hệ tổng hợp',
    'new_contact' => 'Chờ xử lý',
    'pending_contact' => 'Pending',
    'cancel_contact' => 'Hủy',
    'success_contact' => 'Thành công',
    'fail_contact' => 'Sai số',
    'callback_contact' => 'Gọi lại',
    'duplicate_contact' => 'Số trùng',
    'customer_information' => 'Thông tin khách hàng',
    'product' => 'Sản phẩm',
    'customer' => 'Khách hàng',
    'partner' => 'Đối tác',
    'phone' => 'SĐT',
    'zipcode' => 'Mã bưu chính',
    'address' => 'Địa chỉ',
    'district' => 'Quận/Huyện',
    'province' => 'Tỉnh/Thành phố',
    'city' => 'City',
    'country' => 'Quốc gia',
    'payment_method' => 'Hình thức thanh toán',
    'shipping_fee' => 'Phí giao hàng',
    'contact_source' => 'Nguồn liên hệ',
    'order_note' => 'Ghi chú đơn hàng',
    'delivery_note' => 'Ghi chú cho đơn vị vận chuyển',
    'qty' => 'Số lượng',
    'amount' => 'Tổng cộng',
    'total_amount' => 'Tổng đơn',
    'warehouse' => 'Kho',
    'product_type' => 'Loại sản phẩm',
    'available' => 'Khả dụng',
    'save' => 'Lưu',
    'cancel' => 'Hủy',
    'create' => 'Tạo',
    'warehouse_status' => 'Trạng thái kho',
    'create_order' => 'Tạo đơn',
    'buy_option' => 'Yêu cầu',
    'contact_status' => 'Trạng thái',
    'register_time' => 'Ngày ra liên hệ',
    //
    'created_at' => 'Ngày tạo',
    'updated_at' => 'Ngày cập nhật',
    'note' => 'Ghi chú',
    'order_code' => 'Ghi chú đơn hàng',
    'contact_code' => 'Contact code',
    'bill_link' => 'Ảnh chứng từ',
    'delivery_partner' => 'Đối tác vận chuyển',
    'checking_number' => 'Mã vận chuyển đối tác',
    'payment_status' => 'Trạng thái thanh toán',
    'cross_status' => 'Trạng thái đối soát',
    'shipping_status' => 'Trạng thái giao hàng',
    'po_code' => 'PO',
    'order_time' => 'Ngày tạo đơn',
    'sub_transport' => 'Đơn vị vận chuyển',
    'sub_transport_code' => 'Mã đơn vị vận chuyển',
    'cod_cost' => 'tiền COD',
    'time_shipped_success' => 'Ngày giao hàng thành công',
    'collection_fee' => 'Phí thu hộ',
    'transport_fee' => 'Phí vận chuyển',
    'delivery_fee' => 'Phí vận chuyển',
    'cross_check_code' => 'Mã biên bản đối soát',
    'cross_check_time' => 'Ngày đối soát',
    'time_paid_success' => 'Ngày thanh toán',
    'callback_reason' => 'Lý do gọi lại',
    'other_reason' => 'Lý do khác',
    'variant' => 'Thuộc tính',
    'Liên hệ' => '',
    'Lịch sử cuộc gọi' => '',
    'Liên hệ tổng hợp' => '',
    'required_note' => 'Các trường bắt buộc',
    'close' => 'Đóng',
    'call_note' => 'Ghi chú cuộc gọi',
    'ok' => 'OK',
    'callback' => 'Gọi lại',
    'number_fail' => 'Sai số',
    'pending' => 'Pending',
    'duplicate' => 'Trùng',
];
