<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'today_completed' => 'Hoàn thành hôm nay',
    'contact' => 'Liên hệ',
    'contact_histories' => 'Lịch sử cuộc gọi',
    'contact_all' => 'Liên hệ tổng hợp',
    'new_contact' => 'Chờ xử lý',
    'pending_contact' => 'Pending',
    'cancel_contact' => 'Hủy',
    'success_contact' => 'Thành công',
    'fail_contact' => 'Sai số',
    'callback_contact' => 'Gọi lại',
    'duplicate_contact' => 'Số trùng',
    'customer_information' => 'Thông tin khách hàng',
    'product' => 'Sản phẩm',
    'customer' => 'Khách hàng',
    'partner' => 'Đối tác',
    'phone' => 'SĐT',
    'zipcode' => 'Mã bưu chính',
    'address' => 'Địa chỉ',
    'district' => 'Quận/Huyện',
    'province' => 'Tỉnh/Thành phố',
    'city' => 'City',
    'country' => 'Quốc gia',
    'payment_method' => 'Hình thức thanh toán',
    'shipping_fee' => 'Phí giao hàng',
    'contact_source' => 'Nguồn liên hệ',
    'order_note' => 'Ghi chú đơn hàng',
    'delivery_note' => 'Ghi chú cho đơn vị vận chuyển',
    'qty' => 'Số lượng',
    'amount' => 'Tổng cộng',
    'total_amount' => 'Tổng đơn',
    'warehouse' => 'Kho',
    'product_type' => 'Loại sản phẩm',
    'available' => 'Khả dụng',
    'save' => 'Lưu',
    'cancel' => 'Hủy',
    'create' => 'Tạo',
    'warehouse_status' => 'Trạng thái kho',
    'create_order' => 'Tạo đơn',
    'buy_option' => 'Yêu cầu',
    'contact_status' => 'Trạng thái',
    'register_time' => 'Ngày ra liên hệ'
];
